package com.rollo.app

import android.content.Context
import android.webkit.CookieManager
import java.io.File

object XCookies {
    private val HOSTS = listOf(
        "https://x.com",
        "https://twitter.com",
        "https://mobile.twitter.com",
    )

    fun cookiesFile(context: Context): File = File(RolloConfig.dataDir(context), "cookies.txt")

    fun isConnected(context: Context): Boolean {
        val file = cookiesFile(context)
        if (!file.isFile || file.length() < 20) return false
        return file.readText().lines().any { line ->
            val trimmed = line.trim()
            trimmed.isNotEmpty() && !trimmed.startsWith("#") && trimmed.contains("\t")
        }
    }

    fun clear(context: Context) {
        cookiesFile(context).delete()
    }

    fun saveFromCookieManager(context: Context): Boolean {
        val manager = CookieManager.getInstance()
        val lines = mutableListOf(
            "# Netscape HTTP Cookie File",
            "# Generated by Rollo",
        )
        var count = 0
        val expiry = (System.currentTimeMillis() / 1000L) + 365L * 24L * 3600L

        for (host in HOSTS) {
            val raw = manager.getCookie(host) ?: continue
            val domain = host.removePrefix("https://")
            for (part in raw.split(";")) {
                val trimmed = part.trim()
                val eq = trimmed.indexOf('=')
                if (eq <= 0) continue
                val name = trimmed.substring(0, eq).trim()
                val value = trimmed.substring(eq + 1).trim()
                if (name.isEmpty() || value.isEmpty()) continue
                lines.add("$domain\tTRUE\t/\tTRUE\t$expiry\t$name\t$value")
                count++
            }
        }

        if (count == 0) return false
        RolloConfig.dataDir(context).mkdirs()
        cookiesFile(context).writeText(lines.joinToString("\n") + "\n")
        return true
    }
}
