package com.rollo.app

import android.content.Context
import android.webkit.CookieManager
import java.io.File

object XCookies {
    private val HOSTS = listOf(
        "https://x.com",
        "https://twitter.com",
        "https://mobile.twitter.com",
        "https://api.x.com",
    )

    private val AUTH_COOKIE_NAMES = setOf("auth_token", "ct0")

    fun cookiesFile(context: Context): File = File(RolloConfig.dataDir(context), "cookies.txt")

    fun hasAuthCookies(content: String): Boolean {
        return content.lines().any { line ->
            val parts = line.trim().split("\t")
            parts.size >= 7 && AUTH_COOKIE_NAMES.contains(parts[5])
        }
    }

    fun isConnected(context: Context): Boolean {
        val file = cookiesFile(context)
        if (!file.isFile || file.length() < 20) return false
        return hasAuthCookies(file.readText())
    }

    fun clear(context: Context) {
        cookiesFile(context).delete()
    }

    /** Fix legacy files where domain was `x.com` but domain_specified was TRUE. */
    fun repairCookiesFile(context: Context): Boolean {
        val file = cookiesFile(context)
        if (!file.isFile) return false
        val raw = file.readText()
        val repaired = repairNetscapeContent(raw)
        if (repaired == raw) return true
        file.writeText(repaired)
        return true
    }

    fun repairNetscapeContent(raw: String): String {
        val out = mutableListOf<String>()
        for (line in raw.lines()) {
            val trimmed = line.trim()
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                out.add(line)
                continue
            }
            val parts = trimmed.split("\t")
            if (parts.size < 7) {
                out.add(line)
                continue
            }
            val domain = parts[0]
            val domainFlag = parts[1].uppercase()
            val fixedDomain = if (domainFlag == "TRUE" && domain.isNotEmpty() && !domain.startsWith(".")) {
                ".$domain"
            } else {
                domain
            }
            out.add((listOf(fixedDomain) + parts.drop(1)).joinToString("\t"))
        }
        val text = out.joinToString("\n")
        return if (text.endsWith("\n")) text else "$text\n"
    }

    fun saveFromCookieManager(context: Context): Boolean {
        val manager = CookieManager.getInstance()
        manager.flush()

        val lines = mutableListOf(
            "# Netscape HTTP Cookie File",
            "# Generated by Rollo",
        )
        val seen = mutableSetOf<String>()
        var count = 0
        val savedNames = mutableSetOf<String>()
        val expiry = (System.currentTimeMillis() / 1000L) + 365L * 24L * 3600L

        for (host in HOSTS) {
            val raw = manager.getCookie(host) ?: continue
            val hostDomain = host.removePrefix("https://")
            val netscapeDomain = ".$hostDomain"
            for (part in raw.split(";")) {
                val trimmed = part.trim()
                val eq = trimmed.indexOf('=')
                if (eq <= 0) continue
                val name = trimmed.substring(0, eq).trim()
                val value = sanitizeCookieValue(trimmed.substring(eq + 1).trim())
                if (name.isEmpty() || value.isEmpty()) continue
                val key = "$netscapeDomain\t$name"
                if (!seen.add(key)) continue
                lines.add("$netscapeDomain\tTRUE\t/\tTRUE\t$expiry\t$name\t$value")
                savedNames.add(name)
                count++
            }
        }

        if (count == 0) return false
        if (!savedNames.any { AUTH_COOKIE_NAMES.contains(it) }) return false
        RolloConfig.dataDir(context).mkdirs()
        cookiesFile(context).writeText(lines.joinToString("\n") + "\n")
        return true
    }

    private fun sanitizeCookieValue(value: String): String {
        return value
            .replace('\t', ' ')
            .replace('\r', ' ')
            .replace('\n', ' ')
            .trim()
    }
}
